/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard.expenses'
import { Route as DashboardFeatureFlagsRouteImport } from './routes/dashboard.feature-flags'
import { Route as DashboardRevenueRouteImport } from './routes/dashboard.revenue'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard.subscriptions'
import { Route as DashboardWaitlistRouteImport } from './routes/dashboard.waitlist'
import { Route as DashboardSubscriptionsCalendarRouteImport } from './routes/dashboard.subscriptions_.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeatureFlagsRoute = DashboardFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWaitlistRoute = DashboardWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsCalendarRoute =
  DashboardSubscriptionsCalendarRouteImport.update({
    id: '/subscriptions_/calendar',
    path: '/subscriptions/calendar',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/feature-flags': typeof DashboardFeatureFlagsRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/subscriptions/calendar': typeof DashboardSubscriptionsCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/feature-flags': typeof DashboardFeatureFlagsRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/subscriptions/calendar': typeof DashboardSubscriptionsCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/feature-flags': typeof DashboardFeatureFlagsRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/subscriptions_/calendar': typeof DashboardSubscriptionsCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/expenses'
    | '/dashboard/feature-flags'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/waitlist'
    | '/dashboard/'
    | '/dashboard/subscriptions/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/expenses'
    | '/dashboard/feature-flags'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/waitlist'
    | '/dashboard'
    | '/dashboard/subscriptions/calendar'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/expenses'
    | '/dashboard/feature-flags'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/waitlist'
    | '/dashboard/'
    | '/dashboard/subscriptions_/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feature-flags': {
      id: '/dashboard/feature-flags'
      path: '/feature-flags'
      fullPath: '/dashboard/feature-flags'
      preLoaderRoute: typeof DashboardFeatureFlagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenue': {
      id: '/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/waitlist': {
      id: '/dashboard/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/waitlist'
      preLoaderRoute: typeof DashboardWaitlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions_/calendar': {
      id: '/dashboard/subscriptions_/calendar'
      path: '/subscriptions/calendar'
      fullPath: '/dashboard/subscriptions/calendar'
      preLoaderRoute: typeof DashboardSubscriptionsCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardFeatureFlagsRoute: typeof DashboardFeatureFlagsRoute
  DashboardRevenueRoute: typeof DashboardRevenueRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardWaitlistRoute: typeof DashboardWaitlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSubscriptionsCalendarRoute: typeof DashboardSubscriptionsCalendarRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardFeatureFlagsRoute: DashboardFeatureFlagsRoute,
  DashboardRevenueRoute: DashboardRevenueRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardWaitlistRoute: DashboardWaitlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSubscriptionsCalendarRoute: DashboardSubscriptionsCalendarRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
